version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - ./monitoring/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - monitoring

  santander-front-vue:
      build: ./card-system-front-vue
      container_name: santander-front-vue
      ports:
        - "4000:4000"
      networks:
        - monitoring
      depends_on:
        - santander-api

  santander-front-react:
      build: 
        context: ./card-system-front-react
      container_name: santander-front-react
      ports:
        - "4300:4300"      
      environment:
        - CHOKIDAR_USEPOLLING=true
      networks:
        - monitoring
      depends_on:
        - santander-api
  
  santander-front-angular:
      build: 
        context: ./card-system-front-angular
        dockerfile: Dockerfile
      container_name: santander-front-angular
      ports:
        - "4200:4200"
      networks:
        - monitoring
      depends_on:
        - santander-api

  santander-api:
    build: .
    image: card-system-api:1.0
    container_name: santander-api
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.47.1
    container_name: prometheus
    user: root
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - santander-api

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - monitoring
    depends_on:
      - prometheus

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=card_system
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro # Onde colocaremos o script .js
    networks:
      - monitoring

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017/
    networks:
      - monitoring
    depends_on:
      - mongodb

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=santander_system
      - MYSQL_USER=fabiano
      - MYSQL_PASSWORD=admin
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro # Scripts SQL de inicialização
    networks:
      - monitoring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest  # Nome exato da imagem no seu 'docker images'
    container_name: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_ARBITRARY=1
    networks:
      - monitoring
    depends_on:
      - mysqldb

  postgresdb:
    image: postgres:14-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=santander_system
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - monitoring

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      # Importa o servidor automaticamente
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json:ro
      # Importa a senha para não pedir ao clicar no servidor
      - ./pgadmin-config/pgpassfile:/tmp/pgpassfile:ro
    networks:
      - monitoring
    depends_on:
      - postgresdb

  #ollama-server:
  #  image: ollama/ollama:latest
  #  container_name: ollama-server
  #  ports:
  #    - "11434:11434"
  #  volumes:
  #    - ./aiops/ollama_config:/root/.ollama
  #  networks:
  #    - monitoring

  #ai-agent:
  #  build: ./aiops
  #  container_name: ai-agent
  #  depends_on:
  #    - ollama-server
  #  volumes:
  #    - ./aiops/brain:/app/brain
  #    - ./aiops/vector_db:/app/vector_db
  #  networks:
  #    - monitoring      

networks:
  monitoring:
    driver: bridge # Docker cria a rede automaticamente se não existir
