apiVersion: v1
kind: Service
metadata:
  name: santander-card-api-service
spec:
  type: LoadBalancer
  selector:
    app: card-api
  ports:
    - protocol: TCP
      port: 80        # Porta externa
      targetPort: 8080 # Porta interna do container
