name: CI/CD Santander F1RST

on:
  push:
    branches: [ "IaC" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: us-central1
  IMAGE_NAME: card-system-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Ensure State Bucket Exists
        run: |
          # O gcloud e o gsutil agora usarÃ£o a conta autenticada automaticamente
          if ! gsutil ls -b gs://${{ env.PROJECT_ID }}-tfstate >/dev/null 2>&1; then
            gsutil mb -p ${{ env.PROJECT_ID }} -l ${{ env.REGION }} gs://${{ env.PROJECT_ID }}-tfstate
          fi

      - name: Ensure Artifact Registry Repo Exists
        run: |
          if ! gcloud artifacts repositories describe santander-repo --location=${{ env.REGION }} >/dev/null 2>&1; then
            gcloud artifacts repositories create santander-repo \
              --repository-format=docker \
              --location=${{ env.REGION }} \
              --description="Docker repository for Santander API"
          fi

      - name: Docker Auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/santander-repo/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/santander-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="image_name=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ github.sha }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var="image_name=${{ env.IMAGE_NAME }}" \
            -var="image_tag=${{ github.sha }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}